### PR TITLE
FreeRTOS automatic download

### PR DESCRIPTION
**Pull request by aminya**
- This removes FreeRTOS from the repository. It instead adds a script to [download it automatically](https://github.com/IrisSat/IrisSat-Flight-Software/pull/19/files#diff-39f2661726855d51f11d8ed77b62ad6689586b2fb01e524e860f03a709376f78R74).

- It uses [clone](https://github.com/IrisSat/IrisSat-Flight-Software/pull/19/files#diff-62af0a23238bc286a7d1d22fa76fc8a4ff5c8594ce1023d832c53cedfb25a087R35) instead of submodule, and so it is much faster to download. FreeRTOS git tree takes a lot of time to download using submodules.
~- It updates FreeRTOS to "V10.4.2"~

### CODE REVIEW

**Comment by aminya** [comment]
The build works fine. During this process, I updated FreeRTOS to the latest version. Could you check if this does not break the tests?

**Comment by joehowarth17** [comment]
> 
> 
> The build works fine. During this process, I updated FreeRTOS to the latest version. Could you check if this does not break the tests?
> 
> @joehowarth17

The build does not work for me.
It builds without errors, but the executable elf file is basically empty. 
I tried to upload the program, but it won't even complete since it complains about not finding a symbol table. This is kinda expected given there is basically no program to upload.

image

image


Looking through the compiler output there is nothing out of the ordinary, except maybe a linker warning about not finding the reset_handler.

I will keep looking into this.

Out of curiosity, when you build, do you also see a linker warning?
And what size is the program text,data and bss sections?
@aminya

**Comment by aminya** [comment]
I have reverted my commit which removed csp from the libraries section. Now it fails with a more genuine error. For some reason, it tries to use xtensa or something instead of GCC ARM that we want. Maybe we should also update the FreeRTOSConfig.h file

**Comment by aminya** [comment]
The error now changed:
image

I wonder if that is because of this basic change that we had made to FreeRTOS V9 before this PR:
Screenshot 2020-12-12 154000

**Comment by aminya** [comment]
We had to keep MemMang/heap_4.c Now, Error changed again 😄 

image

**Comment by aminya** [comment]
This should work now. I downgraded to V9 which we were using before. 


We were patching FreeRTOS directly instead of doing what I did in https://github.com/IrisSat/IrisSat-Flight-Software/pull/19/commits/0183c3d4aca0216a0d6537523eb7d6a8111d6013

Screenshot 2020-12-12 154000

This is now fixed. 

@joehowarth17

**Comment by joehowarth17** [comment]
> 
> 
> This should work now. I downgraded to V9 which we were using before. We were patching FreeRTOS directly instead of doing what I did in [0183c3d](https://github.com/IrisSat/IrisSat-Flight-Software/commit/0183c3d4aca0216a0d6537523eb7d6a8111d6013)
> 
> Screenshot 2020-12-12 154000
> 
> This is now fixed. Later we can just change `"V9.0.0"` to `"V10.4.2"`, and everythinh should probably work without any changes.
> 
> @joehowarth17

Sweet! I just tried and it's working for me also.

**Comment by aminya** [comment]
Great! I will merge it then!

**Pull request merged**
